/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lmazeaud <lmazeaud@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/05/09 20:38:55 by lmazeaud          #+#    #+#             */
/*   Updated: 2018/07/23 20:06:00 by lmazeaud         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

int		ft_printf(const char *format, ...);
#include <stdio.h>
#include "../includes/ft_printf.h"

void	check(char *s, intmax_t nbr)
{
	printf("%s,%jd,[", s, nbr);
	printf(s, nbr);
	printf("],[");
    fflush(stdout);
    ft_printf(s, nbr);
    printf("]\n");
}


int 	main(int ac, char **av)
{

    // ft_printf("%d\n", ft_printf("1caractere 1 %c caractere 2 %c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("1caractere 1 %c caractere 2 %c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("2caractere 1 %   c caractere 2 % c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("3caractere 1 %   c caractere 2 % c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("4caractere 1 %12c caractere 2 %12c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("4caractere 1 %12c caractere 2 %12c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("4caractere 1 %-12c caractere 2 %-12c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("4caractere 1 %-12c caractere 2 %-12c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("5caractere 1 %0c caractere 2 %0c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("5caractere 1 %0c caractere 2 %0c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("6caractere 1 %012c caractere 2 %012c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("6caractere 1 %012c caractere 2 %012c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("7caractere 1 %-012c caractere 2 %012c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("7caractere 1 %-012c caractere 2 %012c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("8caractere 1 %*c caractere 2 %*c\n", 'a', 6, 6, 6));
    // fflush(stdout);
    // printf("%d\n\n", printf("8caractere 1 %*c caractere 2 %*c\n\n", 'a', 6, 6, 6));

    // ft_printf("%d\n", ft_printf("9caractere 1 %+c caractere 2 %+c\n", 'a', 6, 'c', 6));
    // fflush(stdout);
    // printf("%d\n\n", printf("9caractere 1 %+c caractere 2 %+c\n\n", 'a', 6, 'c', 6));

    // ft_printf("%d\n", ft_printf("10caractere 1 %+12c caractere 2 %+12c\n", 'a', 6, 'c', 6));
    // fflush(stdout);
    // printf("%d\n\n", printf("10caractere 1 %+12c caractere 2 %+12c\n\n", 'a', 6, 'c', 6));

    // ft_printf("%d\n", ft_printf("11caractere 1 %*12c caractere 2 %*12c\n", 'a', -6, 'a', 6));
    // fflush(stdout);
    // printf("%d\n\n", printf("11caractere 1 %*12c caractere 2 %*12c\n\n", 'a', -6, 'a', 6));

    // ft_printf("%d\n", ft_printf("12caractere 1 %-+5c caractere 2 %-+5c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("12caractere 1 %-+5c caractere 2 %-+5c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("13caractere 1 %-+05c caractere 2 %-+05c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("13caractere 1 %-+05c caractere 2 %-+05c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("14caractere 1 %+-5c caractere 2 %+-5c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("14caractere 1 %+-5c caractere 2 %+-5c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("15caractere 1 %.c caractere 2 %.c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("15caractere 1 %.c caractere 2 %.c\n\n", 'a', 'c'));

    // ft_printf("%d\n", ft_printf("16caractere 1 %.6c caractere 2 %.6c\n", 'a', 'c'));
    // fflush(stdout);
    // printf("%d\n\n", printf("16caractere 1 %.6c caractere 2 %.6c\n\n", 'a', 'c'));

    // ft_printf("test 1 : %03d \n test 2 : %03d", -42, 42);
   
  // ft_printf("%d\n", ft_printf("16 chiffre 1 %.6d chiffre 2 %.6d\n", 42, -42));
  //  fflush(stdout);
  // printf("%d\n\n", printf("16 chiffre 1 %.6d chiffre 2 %.6d\n\n", 42, -42));
//   //  fflush(stdout);
// ft_printf("%.d\n", 0);
//   printf("%lu\n", sizeof(char));
//   printf("%lu\n", sizeof(short));
//   printf("%lu\n", sizeof(int));
//   printf("%lu\n", sizeof(long int));
//   printf("%lu\n", sizeof(long long int));
//   printf("%lu\n", sizeof(intmax_t));
//   printf("%lu\n", sizeof(size_t));

    write(1, "\0", 1);
    printf("==== TEST HEX ====\n");
        // check("%x", 512);
        // check("%x", 18);
        // check("%x", -512);
        // check("%x", -18);
        // check("%x", 0);
        // check("%.2x", 0);
        // check("%.3x", 0);
        // check("%.3x", 0);
        // check("%.2x", 10);
        // check("%.3x", 10);
        // check("%.3x", 10);
        // check("%.2x", 0);
        // check("%#x", 0);
        // check("%#x", 1);
        // check("%#x", -1);
        // check("%#x", 16);
        // check("%#x", 455);
        // check("%#x", -455);
    // printf("==== TEST INT ====\n");
    printf("expression,number,printf_result,ft_printf_result\n");
        printf("==== TEST INT ====\n");
            // check("% 03d", 1);
            // check("% 03hd", 1);
            // check("% 03hhd", 1);
            // check("% 03jd", 1);
            // check("% 03ld", 1);
            // check("% 03lld", 1);
            // check("% 03zd", 1);
            // check("% 6d", -3455);
            // check("% 6hd", -3455);
            // check("% 6hhd", -3455);
            // check("% 6jd", -3455);
            // check("% 6ld", -3455);
            // check("% 6lld", -3455);
            // check("% 6zd", -3455);
            // check("% d", -18);
            // check("% d", -2387);
            // check("% d", 2147483647);
            // check("% d", 2387);
            // check("% hd", -18);
            // check("% hd", -2387);
            // check("% hd", 2147483647);
            // check("% hd", 2387);
            // check("% hhd", -18);
            // check("% hhd", -2387);
            // check("% hhd", 2147483647);
            // check("% hhd", 2387);
            // check("% jd", -18);
            // check("% jd", -2387);

            // check("% jd", 2147483647);
            // check("% jd", 2387);
            // check("% ld", -18);
            // check("% ld", -2387);
            // check("% ld", 2147483647);
            // check("% ld", 2387);
            // check("% lld", -18);
            // check("% lld", -2387);
            // check("% lld", 2147483647);
            // check("% lld", 2387);
            // check("% zd", -18);
            // check("% zd", -2387);
            // check("% zd", 2147483647);
            // check("% zd", 2387);
            // check("%+ d", -18);
            // check("%+ d", -2387);
            // check("%+ d", 0);
            // check("%+ d", 2387);
            // check("%+ hd", -18);
            // check("%+ hd", -2387);
            // check("%+ hd", 0);
            // check("%+ hd", 2387);
            // check("%+ hhd", -18);
            // check("%+ hhd", -2387);
            // check("%+ hhd", 0);
            // check("%+ hhd", 2387);
            // check("%+ jd", -18);
            // check("%+ jd", -2387);
            // check("%+ jd", 0);
            // check("%+ jd", 2387);
            // check("%+ ld", -18);
            // check("%+ ld", -2387);

            // check("%+ ld", 0);
            // check("%+ ld", 2387);
            // check("%+ lld", -18);
            // check("%+ lld", -2387);
            // check("%+ lld", 0);
            // check("%+ lld", 2387);
            // check("%+ zd", -18);
            // check("%+ zd", -2387);
            // check("%+ zd", 0);
            // check("%+ zd", 2387);
            // check("%+03d", 1); 
            // check("%+03hd", 1); 
            // check("%+03hhd", 1); 
            // check("%+03jd", 1); 
            // check("%+03ld", 1); 
            // check("%+03lld", 1); 
            // check("%+03zd", 1); 
            // check("%+d", -18);
            // check("%+d", -2387);
            // check("%+d", 0);
            // check("%+d", 2387);
            // check("%+hd", -18);
            // check("%+hd", -2387);
            // check("%+hd", 0);
            // check("%+hd", 2387);
            // check("%+hhd", -18);
            // check("%+hhd", -2387);
            // check("%+hhd", 0);
            // check("%+hhd", 2387);
            // check("%+jd", -18);
            // check("%+jd", -2387);
            // check("%+jd", 0);
            // check("%+jd", 2387);
            // check("%+ld", -18);
            // check("%+ld", -2387);
            // check("%+ld", 0);
            // check("%+ld", 2387);
            // check("%+lld", -18);
            // check("%+lld", -2387);
            // check("%+lld", 0);

            // check("%+lld", 2387);
            // check("%+zd", -18);
            // check("%+zd", -2387);
            // check("%+zd", 0);
            // check("%+zd", 2387);
            // check("%-+6d", -455);
            // check("%-+6d", 455);
            // check("%-+6hd", -455);
            // check("%-+6hd", 455);
            // check("%-+6hhd", -455);
            // check("%-+6hhd", 455);
            // check("%-+6jd", -455);
            // check("%-+6jd", 455);
            // check("%-+6ld", -455);
            // check("%-+6ld", 455);
            // check("%-+6lld", -455);
            // check("%-+6lld", 455);
            // check("%-+6zd", -455);
            // check("%-+6zd", 455);
            // check("%-15d", -2147483648);
            // check("%-15d", 2147483647);
            // check("%-15hd", -2147483648);
            // check("%-15hd", 2147483647);
            // check("%-15hhd", -2147483648);
            // check("%-15hhd", 2147483647);
            // check("%-15jd", -2147483648);
            // check("%-15jd", 2147483647);
            // check("%-15ld", -2147483648);
            // check("%-15ld", 2147483647);
            // check("%-15lld", -2147483648);
            // check("%-15lld", 2147483647);
            // check("%-15zd", -2147483648);
            // check("%-15zd", 2147483647);
            // check("%-3d", -18);
            // check("%-3d", -2387);
            // check("%-3d", 0);
            // check("%-3d", 2387);
            // check("%-3hd", -18);
            // check("%-3hd", -2387);
            // check("%-3hd", 0);
            // check("%-3hd", 2387);
            // check("%-3hhd", -18);
            // check("%-3hhd", -2387);
            // check("%-3hhd", 0);
            // check("%-3hhd", 2387);
            // check("%-3jd", -18);
            // check("%-3jd", -2387);
            // check("%-3jd", 0);
            // check("%-3jd", 2387);
            // check("%-3ld", -18);
            // check("%-3ld", -2387);
            // check("%-3ld", 0);
            // check("%-3ld", 2387);
            // check("%-3lld", -18);
            // check("%-3lld", -2387);
            // check("%-3lld", 0);
            // check("%-3lld", 2387);
            // check("%-3zd", -18);
            // check("%-3zd", -2387);
            // check("%-3zd", 0);
            // check("%-3zd", 2387);
            // check("%-6d", -3455);
            // check("%-6hd", -3455);
            // check("%-6hhd", -3455);
            // check("%-6jd", -3455);
            // check("%-6ld", -3455);
            // check("%-6lld", -3455);
            // check("%-6zd", -3455);
            // check("%-d", -2147483648);
            // check("%-d", 2147483647);
            // check("%-hd", -2147483648);
            // check("%-hd", 2147483647);
            // check("%-hhd", -2147483648);
            // check("%-hhd", 2147483647);
            // check("%-jd", -2147483648);
            // check("%-jd", 2147483647);
            // check("%-ld", -2147483648);
            // check("%-ld", 2147483647);
            // check("%-lld", -2147483648);
            // check("%-lld", 2147483647);
            // check("%-zd", -2147483648);
            // check("%-zd", 2147483647);
            // check("%.3d", -18);
            // check("%.3d", -2387);
            // check("%.3d", 0);
            // check("%.3d", 2387);
            // check("%.3hd", -18);
            // check("%.3hd", -2387);
            // check("%.3hd", 0);
            // check("%.3hd", 2387);
            // check("%.3hhd", -18);
            // check("%.3hhd", -2387);
            // check("%.3hhd", 0);
            // check("%.3hhd", 2387);
            // check("%.3jd", -18);
            // check("%.3jd", -2387);
            // check("%.3jd", 0);
            // check("%.3jd", 2387);
            // check("%.3ld", -18);
            // check("%.3ld", -2387);
            // check("%.3ld", 0);
            // check("%.3ld", 2387);
            // check("%.3lld", -18);

            // check("%.3lld", -2387);
            // check("%.3lld", 0);
            // check("%.3lld", 2387);
            // check("%.3zd", -18);
            // check("%.3zd", -2387);
            // check("%.3zd", 0);
            // check("%.3zd", 2387);
            // check("%.d", -5);
            // check("%.d", 0);
            // check("%.d", 5);
            // check("%.hd", -5);
            // check("%.hd", 0);
            // check("%.hd", 5);
            // check("%.hhd", -5);
            // check("%.hhd", 0);
            // check("%.hhd", 5);
            // check("%.jd", -5);
            // check("%.jd", 0);
            // check("%.jd", 5);
            // check("%.ld", -5);
            // check("%.ld", 0);
            // check("%.ld", 5);
            // check("%.lld", -5);
            // check("%.lld", 0);
            // check("%.lld", 5);
            // check("%.zd", -5);
            // check("%.zd", 0);
            // check("%.zd", 5);
            // check("%0-10d", 10);
            // check("%0-10hd", 10);
            // check("%0-10hhd", 10);
            // check("%0-10jd", 10);
            // check("%0-10ld", 10);
            // check("%0-10lld", 10);
            // check("%0-10zd", 10);
            // check("%0.2d", -5);
            // check("%0.2d", 0); //segfault
            // check("%0.2d", 5);
            // check("%0.2hd", -5);
            // check("%0.2hd", 0);
            // check("%0.2hd", 5);
            // check("%0.2hhd", -5);
            // check("%0.2hhd", 0);
            // check("%0.2hhd", 5);
            // check("%0.2jd", -5);
            // check("%0.2jd", 0);
            // check("%0.2jd", 5);
            // check("%0.2ld", -5);
            // check("%0.2ld", 0);
            // check("%0.2ld", 5);
            // check("%0.2lld", -5);
            // check("%0.2lld", 0);
            // check("%0.2lld", 5);
            // check("%0.2zd", -5);
            // check("%0.2zd", 0);
            // check("%0.2zd", 5);
            // check("%0.8d", -346);
            
            // check("%8.8d", 346);
            // check("%8.8hd", -346);
            // check("%8.8hd", 346);
            // check("%8.8hhd", -346);
            // check("%8.8hhd", 346);
            // check("%8.8jd", -346);
            // check("%8.8jd", 346);
            // check("%8.8ld", -346);
            // check("%8.8ld", 346);
            // check("%8.8lld", -346);
            // check("%8.8lld", 346);
            // check("%8.8zd", -346);
            // check("%8.8zd", 346);

            // check("%+8.8d", 346);
            // check("%+8.8hd", -346);
            // check("%+8.8hd", 346);
            // check("%+8.8hhd", -346);
            // check("%+8.8hhd", 346);
            // check("%+8.8jd", -346);
            // check("%+8.8jd", 346);
            // check("%+8.8ld", -346);
            // check("%+8.8ld", 346);
            // check("%+8.8lld", -346);
            // check("%+8.8lld", 346);
            // check("%+8.8zd", -346);
            // check("%+8.8zd", 346);

            // check("%-8.8d", 346);
            // check("%-8.8hd", -346);
            // check("%-8.8hd", 346);
            // check("%-8.8hhd", -346);
            // check("%-8.8hhd", 346);
            // check("%-8.8jd", -346);
            // check("%-8.8jd", 346);
            // check("%-8.8ld", -346);
            // check("%-8.8ld", 346);
            // check("%-8.8lld", -346);
            // check("%-8.8lld", 346);
            // check("%-8.8zd", -346);
            // check("%-8.8zd", 346);
    
            // check("%-+8.8d", 346);
            // check("%-+8.8hd", -346);
            // check("%-+8.8hd", 346);
            // check("%-+8.8hhd", -346);
            // check("%-+8.8hhd", 346);
            // check("%-+8.8jd", -346);
            // check("%-+8.8jd", 346);
            // check("%-+8.8ld", -346);
            // check("%-+8.8ld", 346);
            // check("%-+8.8lld", -346);
            // check("%-+8.8lld", 346);
            // check("%-+8.8zd", -346);
            // check("%-+8.8zd", 346);

            // check("%0.8d", 346);
            // check("%0.8hd", -346);
            // check("%0.8hd", 346);
            // check("%0.8hhd", -346);
            // check("%0.8hhd", 346);
            // check("%0.8jd", -346);
            // check("%0.8jd", 346);
            // check("%0.8ld", -346);
            // check("%0.8ld", 346);
            // check("%0.8lld", -346);
            // check("%0.8lld", 346);
            // check("%0.8zd", -346);
            // check("%0.8zd", 346);
            // check("%03.4d", -100);
            // check("%03.4d", -1000);
            // check("%03.4d", -4);
            // check("%03.4d", 0);
            // check("%03.4d", 100);
            // check("%03.4d", 1000);
            // check("%03.4d", 4);
            // check("%03.4hd", -100);
            // check("%03.4hd", -1000);
            // check("%03.4hd", -4);
            // check("%03.4hd", 0);
            // check("%03.4hd", 100);
            // check("%03.4hd", 1000);
            // check("%03.4hd", 4);
            // check("%03.4hhd", -100);
            // check("%03.4hhd", -1000);
            // check("%03.4hhd", -4);
            // check("%03.4hhd", 0);
            // check("%03.4hhd", 100);
            // check("%03.4hhd", 1000);
            // check("%03.4hhd", 4);
            // check("%03.4jd", -100);
            // check("%03.4jd", -1000);
            // check("%03.4jd", -4);
            // check("%03.4jd", 0);
            // check("%03.4jd", 100);
            // check("%03.4jd", 1000);
            // check("%03.4jd", 4);
            // check("%03.4ld", -100);
            // check("%03.4ld", -1000);
            // check("%03.4ld", -4);
            // check("%03.4ld", 0);
            // check("%03.4ld", 100);
            // check("%03.4ld", 1000);
            // check("%03.4ld", 4);
            // check("%03.4lld", -100);
            // check("%03.4lld", -1000);
            // check("%03.4lld", -4);
            // check("%03.4lld", 0);
            // check("%03.4lld", 100);
            // check("%03.4lld", 1000);
            // check("%03.4lld", 4);
            // check("%03.4zd", -100);
            // check("%03.4zd", -1000);
            // check("%03.4zd", -4);
            // check("%03.4zd", 0);
            // check("%03.4zd", 100);
            // check("%03.4zd", 1000);
            // check("%03.4zd", 4);
            // check("%03.d", -1);
            // check("%03.d", -4);
            // check("%03.d", 0);
            // check("%03.d", 1);
            // check("%03.d", 4);
            // check("%03.hd", -1);
            // check("%03.hd", -4);
            // check("%03.hd", 0);
            // check("%03.hd", 1);
            // check("%03.hd", 4);
            // check("%03.hhd", -1);
            // check("%03.hhd", -4);
            // check("%03.hhd", 0);
            // check("%03.hhd", 1);
            // check("%03.hhd", 4);
            // check("%03.jd", -1);
            // check("%03.jd", -4);
            // check("%03.jd", 0);
            // check("%03.jd", 1);
            // check("%03.jd", 4);
            // check("%03.ld", -1);
            // check("%03.ld", -4);
            // check("%03.ld", 0);
            // check("%03.ld", 1);
            // check("%03.ld", 4);
            // check("%03.lld", -1);
            // check("%03.lld", -4);
            // check("%03.lld", 0);
            // check("%03.lld", 1);
            // check("%03.lld", 4);
            // check("%03.zd", -1);
            // check("%03.zd", -4);
            // check("%03.zd", 0);
            // check("%03.zd", 1);
            // check("%03.zd", 4);
            // check("%03d", -1);
            // check("%03d", -4);
            // check("%03d", 0);
            // check("%03d", 1);
            // check("%03d", 4);
            // check("%03hd", -1);
            // check("%03hd", -4);
            // check("%03hd", 0);
            // check("%03hd", 1);
            // check("%03hd", 4);
            // check("%03hhd", -1);
            // check("%03hhd", -4);
            // check("%03hhd", 0);
            // check("%03hhd", 1);
            // check("%03hhd", 4);
            // check("%03jd", -1);
            // check("%03jd", -4);
            // check("%03jd", 0);
            // check("%03jd", 1);
            // check("%03jd", 4);
            // check("%03ld", -1);
            // check("%03ld", -4);
            // check("%03ld", 0);
            // check("%03ld", 1);
            // check("%03ld", 4);
            // check("%03lld", -1);
            // check("%03lld", -4);
            // check("%03lld", 0);
            // check("%03lld", 1);
            // check("%03lld", 4);
            // check("%03zd", -1);
            // check("%03zd", -4);
            // check("%03zd", 0);
            // check("%03zd", 1);
            // check("%03zd", 4);
            // check("%06d", -2356);
            // check("%06hd", -2356);
            // check("%06hhd", -2356);
            // check("%06jd", -2356);
            // check("%06ld", -2356);
            // check("%06lld", -2356);
            // check("%06zd", -2356);
            // check("%2.1d", -5);
            // check("%2.1d", 0);
            // check("%2.1d", 5);
            // check("%2.1hd", -5);
            // check("%2.1hd", 0);
            // check("%2.1hd", 5);
            // check("%2.1hhd", -5);
            // check("%2.1hhd", 0);
            // check("%2.1hhd", 5);
            // check("%2.1jd", -5);
            // check("%2.1jd", 0);
            // check("%2.1jd", 5);
            // check("%2.1ld", -5);
            // check("%2.1ld", 0);
            // check("%2.1ld", 5);
            // check("%2.1lld", -5);
            // check("%2.1lld", 0);
            // check("%2.1lld", 5);
            // check("%2.1zd", -5);
            // check("%2.1zd", 0);
            // check("%2.1zd", 5);
            // check("%2.2d", -5);
            // check("%2.2d", 0);
            // check("%2.2d", 5);
            // check("%2.2hd", -5);
            // check("%2.2hd", 0);
            // check("%2.2hd", 5);
            // check("%2.2hhd", -5);
            // check("%2.2hhd", 0);
            // check("%2.2hhd", 5);
            // check("%2.2jd", -5);
            // check("%2.2jd", 0);
            // check("%2.2jd", 5);
            // check("%2.2ld", -5);
            // check("%2.2ld", 0);
            // check("%2.2ld", 5);
            // check("%2.2lld", -5);
            // check("%2.2lld", 0);
            // check("%2.2lld", 5);
            // check("%2.2zd", -5);
            // check("%2.2zd", 0);
            // check("%2.2zd", 5);
            // check("%2.3d", -5);
            // check("%2.3d", 0);
            // check("%2.3d", 5);
            // check("%2.3hd", -5);
            // check("%2.3hd", 0);
            // check("%2.3hd", 5);
            // check("%2.3hhd", -5);
            // check("%2.3hhd", 0);
            // check("%2.3hhd", 5);
            // check("%2.3jd", -5);
            // check("%2.3jd", 0);
            // check("%2.3jd", 5);
            // check("%2.3ld", -5);
            // check("%2.3ld", 0);
            // check("%2.3ld", 5);
            // check("%2.3lld", -5);
            // check("%2.3lld", 0);
            // check("%2.3lld", 5);
            // check("%2.3zd", -5);
            // check("%2.3zd", 0);
            // check("%2.3zd", 5);
            // check("%2.6d", -346);
            // check("%2.6d", 346);
            // check("%2.6hd", -346);
            // check("%2.6hd", 346);
            // check("%2.6hhd", -346);
            // check("%2.6hhd", 346);
            // check("%2.6jd", -346);
            // check("%2.6jd", 346);
            // check("%2.6ld", -346);
            // check("%2.6ld", 346);
            // check("%2.6lld", -346);
            // check("%2.6lld", 346);
            // check("%2.6zd", -346);
            // check("%2.6zd", 346);
            // check("%3.2d", -5);
            // check("%3.2d", 0);
            // check("%3.2d", 5);
            // check("%3.2hd", -5);
            // check("%3.2hd", 0);
            // check("%3.2hd", 5);
            // check("%3.2hhd", -5);
            // check("%3.2hhd", 0);
            // check("%3.2hhd", 5);
            // check("%3.2jd", -5);
            // check("%3.2jd", 0);
            // check("%3.2jd", 5);
            // check("%3.2ld", -5);
            // check("%3.2ld", 0);
            // check("%3.2ld", 5);
            // check("%3.2lld", -5);
            // check("%3.2lld", 0);
            // check("%3.2lld", 5);
            // check("%3.2zd", -5);
            // check("%3.2zd", 0);
            // check("%3.2zd", 5);
            // check("%3.7d", -346);
            // check("%3.7d", -5);
            // check("%3.7d", 0);
            // check("%3.7d", 346);
            // check("%3.7d", 5);
            // check("%3.7hd", -346);
            // check("%3.7hd", -5);
            // check("%3.7hd", 0);
            // check("%3.7hd", 346);
            // check("%3.7hd", 5);
            // check("%3.7hhd", -346);
            // check("%3.7hhd", -5);
            // check("%3.7hhd", 0);
            // check("%3.7hhd", 346);
            // check("%3.7hhd", 5);
            // check("%3.7jd", -346);
            // check("%3.7jd", -5);
            // check("%3.7jd", 0);
            // check("%3.7jd", 346);
            // check("%3.7jd", 5);
            // check("%3.7ld", -346);
            // check("%3.7ld", -5);
            // check("%3.7ld", 0);
            // check("%3.7ld", 346);
            // check("%3.7ld", 5);
            // check("%3.7lld", -346);
            // check("%3.7lld", -5);
            // check("%3.7lld", 0);
            // check("%3.7lld", 346);
            // check("%3.7lld", 5);
            // check("%3.7zd", -346);
            // check("%3.7zd", -5);
            // check("%3.7zd", 0);
            // check("%3.7zd", 346);
            // check("%3.7zd", 5);
            // check("%3d", -18);
            // check("%3d", -2387);
            // check("%3d", 0);
            // check("%3d", 2387);
            // check("%3hd", -18);
            // check("%3hd", -2387);
            // check("%3hd", 0);
            // check("%3hd", 2387);
            // check("%3hhd", -18);
            // check("%3hhd", -2387);
            // check("%3hhd", 0);
            // check("%3hhd", 2387);
            // check("%3jd", -18);
            // check("%3jd", -2387);
            // check("%3jd", 0);
            // check("%3jd", 2387);
            // check("%3ld", -18);
            // check("%3ld", -2387);
            // check("%3ld", 0);
            // check("%3ld", 2387);
            // check("%3lld", -18);
            // check("%3lld", -2387);
            // check("%3lld", 0);
            // check("%3lld", 2387);
            // check("%3zd", -18);
            // check("%3zd", -2387);
            // check("%3zd", 0);
            // check("%3zd", 2387);
            // check("%5.0d", -5);
            // check("%5.0d", 5);
            // check("%5.0hd", -5);
            // check("%5.0hd", 5);
            // check("%5.0hhd", -5);
            // check("%5.0hhd", 5);
            // check("%5.0jd", -5);
            // check("%5.0jd", 5);
            // check("%5.0ld", -5);
            // check("%5.0ld", 5);
            // check("%5.0lld", -5);
            // check("%5.0lld", 5);
            // check("%5.0zd", -5);
            // check("%5.0zd", 5);
            // check("%5.3d", -346);
            // check("%5.3d", 346);
            // check("%5.3hd", -346);
            // check("%5.3hd", 346);
            // check("%5.3hhd", -346);
            // check("%5.3hhd", 346);
            // check("%5.3jd", -346);
            // check("%5.3jd", 346);
            // check("%5.3ld", -346);
            // check("%5.3ld", 346);
            // check("%5.3lld", -346);
            // check("%5.3lld", 346);
            // check("%5.3zd", -346);
            // check("%5.3zd", 346);
            // check("%6.2d", -346);
            // check("%6.2d", 346);
            // check("%6.2hd", -346);
            // check("%6.2hd", 346);
            // check("%6.2hhd", -346);
            // check("%6.2hhd", 346);
            // check("%6.2jd", -346);
            // check("%6.2jd", 346);
            // check("%6.2ld", -346);
            // check("%6.2ld", 346);
            // check("%6.2lld", -346);
            // check("%6.2lld", 346);
            // check("%6.2zd", -346);
            // check("%6.2zd", 346);
            // check("%7.1d", -346);
            // check("%7.1d", 346);
            // check("%7.1hd", -346);
            // check("%7.1hd", 346);
            // check("%7.1hhd", -346);
            // check("%7.1hhd", 346);
            // check("%7.1jd", -346);
            // check("%7.1jd", 346);
            // check("%7.1ld", -346);
            // check("%7.1ld", 346);
            // check("%7.1lld", -346);
            // check("%7.1lld", 346);
            // check("%7.1zd", -346);
            // check("%7.1zd", 346);
            // check("%7.3d", -346);
            // check("%7.3d", -5);
            // check("%7.3d", 0);
            // check("%7.3d", 346);
            // check("%7.3d", 5);
            // check("%7.3hd", -346);
            // check("%7.3hd", -5);
            // check("%7.3hd", 0);
            // check("%7.3hd", 346);
            // check("%7.3hd", 5);
            // check("%7.3hhd", -346);
            // check("%7.3hhd", -5);
            // check("%7.3hhd", 0);
            // check("%7.3hhd", 346);
            // check("%7.3hhd", 5);
            // check("%7.3jd", -346);
            // check("%7.3jd", -5);
            // check("%7.3jd", 0);
            // check("%7.3jd", 346);
            // check("%7.3jd", 5);
            // check("%7.3ld", -346);
            // check("%7.3ld", -5);
            // check("%7.3ld", 0);
            // check("%7.3ld", 346);
            // check("%7.3ld", 5);
            // check("%7.3lld", -346);
            // check("%7.3lld", -5);
            // check("%7.3lld", 0);
            // check("%7.3lld", 346);
            // check("%7.3lld", 5);
            // check("%7.3zd", -346);
            // check("%7.3zd", -5);
            // check("%7.3zd", 0);
            // check("%7.3zd", 346);
            // check("%7.3zd", 5);
            // check("%8.0d", -346);
            // check("%8.0d", 346);
            // check("%8.0hd", -346);
            // check("%8.0hd", 346);
            // check("%8.0hhd", -346);
            // check("%8.0hhd", 346);
            // check("%8.0jd", -346);
            // check("%8.0jd", 346);
            // check("%8.0ld", -346);
            // check("%8.0ld", 346);
            // check("%8.0lld", -346);
            // check("%8.0lld", 346);
            // check("%8.0zd", -346);
            // check("%8.0zd", 346);
            // check("%d", -18);
            // check("%d", -2147483648);
            // check("%d", -2387);
            // check("%d", -5);
            // check("%d", 1);
            // check("%d", 18);
            // check("%d", 2147483647);
            // check("%d", 2387);
            // check("%d", 5);
            // check("%hd", -18);
            // check("%hd", -2147483648);
            // check("%hd", -2387);
            // check("%hd", -5);
            // check("%hd", 1);
            // check("%hd", 18);
            // check("%hd", 2147483647);
            // check("%hd", 2387);
            // check("%hd", 5);
            // check("%hhd", -18);
            // check("%hhd", -2147483648);
            // check("%hhd", -2387);
            // check("%hhd", -5);
            // check("%hhd", 1);
            // check("%hhd", 18);
            // check("%hhd", 2147483647);
            // check("%hhd", 2387);
            // check("%hhd", 5);
            // check("%jd", -18);
            // check("%jd", -2147483648);
            // check("%jd", -2387);
            // check("%jd", -5);
            // check("%jd", 1);
            // check("%jd", 18);
            // check("%jd", 2147483647);
            // check("%jd", 2387);
            // check("%jd", 5);
            // check("%ld", -18);
            // check("%ld", -2147483648);
            // check("%ld", -2387);
            // check("%ld", -5);
            // check("%ld", 1);
            // check("%ld", 18);
            // check("%ld", 2147483647);
            // check("%ld", 2387);
            // check("%ld", 5);
            // check("%lld", -18);
            // check("%lld", -2147483648);
            // check("%lld", -2387);
            // check("%lld", -5);
            // check("%lld", 1);
            // check("%lld", 18);
            // check("%lld", 2147483647);
            // check("%lld", 2387);
            // check("%lld", 5);
            // check("%zd", -18);
            // check("%zd", -2147483648);
            // check("%zd", -2387);
            // check("%zd", -5);
            // check("%zd", 1);
            // check("%zd", 18);
            // check("%zd", 2147483647);
            // check("%zd", 2387);
            // check("%zd", 5);
        printf("==== TEST CHAR ====\n");
            check("%.2c", NULL);                 
            check("%c", 42);                     
            check("%5c", 42);                    
            check("%-5c", 42);                  
            check("@moulitest: %c", 0);          
            check("%2c", 0);                     
            check("null %c and text", 0);        
            check("% c", 0);                     
            check("%-010c", 'a');
            check("%010.5c", 'a');
            check("%c", 'A');
            check("%c", -'a');
            check("%c", 127);
            check("%c", -128);
            check("%c", 0);
            check("%3c", 'a');
            check("%3c", 'A');
            check("%3c", -'a');
            check("%3c", 127);
            check("%3c", -128);
            check("%3c", 0);
            check("%6c", 'a');
            check("%-3c", 'a');
            check("%-3c", 'A');
            check("%-3c", -'a');
            check("%-3c", 127);
            check("%-3c", -128);
            check("%-3c", 0);
            check("%c", 0);
            check("%c", 'a');
            check("%c", '0');
            check("%.0c", '0');
            check("%.3c", '0');
            check("%.7c", '0');
            check("%0.3c", '0');
            check("%1.3c", '0');
            check("%3.3c", '0');
            check("%5.3c", '0');
            check("%00.3c", '0');
            check("%01.3c", '0');
            check("%03.3c", '0');
            check("%03.3c", 256);
            check("%03.3c", 310);
            check("%03.3c", -'a');
            check("%6hc", 'a');
            check("%hc", 'a');
            check("%hc", 'A');
            check("%hc", -'a');
            check("%hc", 127);
            check("%hc", -128);
            check("%hc", 0);
            check("%3hc", 'a');
            check("%3hc", 'A');
            check("%3hc", -'a');
            check("%3hc", 127);
            check("%3hc", -128);
            check("%3hc", 0);
            check("%-3hc", 'a');
            check("%-3hc", 'A');
            check("%-3hc", -'a');
            check("%-3hc", 127);
            check("%-3hc", -128);
            check("%-3hc", 0);
            check("%hc", 0);
            check("%hc", 'a');
            check("%hc", '0');
            check("%.0hc", '0');
            check("%.3hc", '0');
            check("%.7hc", '0');
            check("%0.3hc", '0');
            check("%1.3hc", '0');
            check("%3.3hc", '0');
            check("%5.3hc", '0');
            check("%00.3hc", '0');
            check("%01.3hc", '0');
            check("%03.3hc", '0');
            check("%05.3hc", '0');
            check("%6hhc", 'a');
            check("%hhc", 'a');
            check("%hhc", 'A');
            check("%hhc", -'a');
            check("%hhc", 127);
            check("%hhc", -128);
            check("%hhc", 0);
            check("%3hhc", 'a');
            check("%3hhc", 'A');
            check("%3hhc", -'a');
            check("%3hhc", 127);
            check("%3hhc", -128);
            check("%3hhc", 0);
            check("%-3hhc", 'a');
            check("%-3hhc", 'A');
            check("%-3hhc", -'a');
            check("%-3hhc", 127);
            check("%-3hhc", -128);
            check("%-3hhc", 0);
            check("%hhc", 0);
            check("%hhc", 'a');
            check("%hhc", '0');
            check("%.0hhc", '0');
            check("%.3hhc", '0');
            check("%.7hhc", '0');
            check("%0.3hhc", '0');
            check("%1.3hhc", '0');
            check("%3.3hhc", '0');
            check("%5.3hhc", '0');
            check("%00.3hhc", '0');
            check("%01.3hhc", '0');
            check("%03.3hhc", '0');
            check("%05.3hhc", '0');
            check("%6lc", 'a');
            check("%lc", 'a');
            check("%lc", 'A');
            check("%lc", 127);
            check("%lc", 0);
            check("%3lc", 'a');
            check("%3lc", 'A');
            check("%3lc", 127);
            check("%3lc", 0);
            check("%-3lc", 'a');
            check("%-3lc", 'A');
            check("%-3lc", 127);
            check("%-3lc", 0);
            check("%lc", 0);
            check("%lc", 'a');
            check("%lc", '0');
            check("%.0lc", '0');
            check("%.3lc", '0');
            check("%.7lc", '0');
            check("%0.3lc", '0');
            check("%1.3lc", '0');
            check("%3.3lc", '0');
            check("%5.3lc", '0');
            check("%00.3lc", '0');
            check("%01.3lc", '0');
            check("%03.3lc", '0');
            check("%05.3lc", '0');
            check("%6llc", 'a');
            check("%llc", 'a');
            check("%llc", 'A');
            check("%llc", 127);
            check("%llc", 0);
            check("%3llc", 'a');
            check("%3llc", 'A');
            check("%3llc", 127);
            check("%3llc", 0);
            check("%-3llc", 'a');
            check("%-3llc", 'A');
            check("%-3llc", 127);
            check("%-3llc", 0);
            check("%llc", 0);
            check("%llc", 'a');
            check("%llc", '0');
            check("%.0llc", '0');
            check("%.3llc", '0');
            check("%.7llc", '0');
            check("%0.3llc", '0');
            check("%1.3llc", '0');
            check("%3.3llc", '0');
            check("%5.3llc", '0');
            check("%00.3llc", '0');
            check("%01.3llc", '0');
            check("%03.3llc", '0');
            check("%05.3llc", '0');
            check("%6zc", 'a');
            check("%zc", 'a');
            check("%zc", 'A');
            check("%zc", -'a');
            check("%zc", 127);
            check("%zc", -128);
            check("%zc", 0);
            check("%3zc", 'a');
            check("%3zc", 'A');
            check("%3zc", -'a');
            check("%3zc", 127);
            check("%3zc", -128);
            check("%3zc", 0);
            check("%-3zc", 'a');
            check("%-3zc", 'A');
            check("%-3zc", -'a');
            check("%-3zc", 127);
            check("%-3zc", -128);
            check("%-3zc", 0);
            check("%zc", 0);
            check("%zc", 'a');
            check("%zc", '0');
            check("%.0zc", '0');
            check("%.3zc", '0');
            check("%.7zc", '0');
            check("%0.3zc", '0');
            check("%1.3zc", '0');
            check("%3.3zc", '0');
            check("%5.3zc", '0');
            check("%00.3zc", '0');
            check("%01.3zc", '0');
            check("%03.3zc", '0');
            check("%05.3zc", '0');
            check("%6jc", 'a');
            check("%jc", 'a');
            check("%jc", 'A');
            check("%jc", -'a');
            check("%jc", 127);
            check("%jc", -128);
            check("%jc", 0);
            check("%3jc", 'a');
            check("%3jc", 'A');
            check("%3jc", -'a');
            check("%3jc", 127);
            check("%3jc", -128);
            check("%3jc", 0);
            check("%-3jc", 'a');
            check("%-3jc", 'A');
            check("%-3jc", -'a');
            check("%-3jc", 127);
            check("%-3jc", -128);
            check("%-3jc", 0);
            check("%jc", 0);
            check("%jc", 'a');
            check("%jc", '0');
            check("%.0jc", '0');
            check("%.3jc", '0');
            check("%.7jc", '0');
            check("%0.3jc", '0');
            check("%1.3jc", '0');
            check("%3.3jc", '0');
            check("%5.3jc", '0');
            check("%00.3jc", '0');
            check("%01.3jc", '0');
            check("%03.3jc", '0');
            check("%05.3jc", '0');
            check("%05.3jc", '0');
            check("%+c", 'A');
            check("%+c", -'a');
            check("%+c", 127);
            check("%+c", -128);
            check("%+c", 0);
            check("%+3c", 'a');
            check("%+3c", 'A');
            check("%+3c", -'a');
            check("%+3c", 127);
            check("%+3c", -128);
            check("%+3c", 0);
            check("%+6c", 'a');
            check("%+-3c", 'a');
            check("%+-3c", 'A');
            check("%+-3c", -'a');
            check("%+-3c", 127);
            check("%+-3c", -128);
            check("%+-3c", 0);
}

